// Even Fibonacci numbers
// Problem 2
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

//Step 1: create array of Fibonacci numbers up to 4 million.

var fibArray = [1, 2];
var a = 1;
var b = 2;

while (b <= 4000000) {
	c = a + b;
	fibArray.push(c);
	a = b;
	b = c;
}

// Step 2: add up all the even numbers in the array.


